version: "3"
services:
  node:
    build:
      context: .
      dockerfile: builder.Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - .:/usr/app
    environment:
      NODE_ENV: development
